# Name of website
title: ConverterPro
description: ConverterPro is a Python library that allows developers to convert units easily.

# Your name to show in the footer
author: Lily Oforiwa Sam

remote_theme: pages-themes/leap-day@v0.2.0

# Exclude these files from production site
exclude:
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme