site_name: ConverterPro
site_url: https://oforiwaasam.github.io/converterpro/
repo_url: https://github.com/oforiwaasam/converterpro
repo_name: oforiwaasam/converterpro
site_description: A unit conversion library in Python
copyright: |
  Copyright &copy; 2023 <a href="https://github.com/oforiwaasam"  target="_blank">Lily Sam</a>
watch:
  - converterpro
  - README.md
  - LICENSE
  - CONTRIBUTING.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            show_submodules: no
  - include-markdown

nav:
- Home:
  - Overview: index.md
  - License: license.md
- User Guide:
  - Weight Converter: weight_converter_usage.md
- API Reference: 
  - Weight Converter: weight_converter_reference.md
- Development:
  - Contributing: contributing.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
  icon: 
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-blue
      accent: deep-blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-blue
      accent: deep-blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
