name: CI/CD

on:
  push:
    branches: [ 'main', 'hw4-hw5' ]
    paths-ignore: [ 'CONTRIBUTING.md', 'LICENSE', 'README.md']
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install poetry
      run: |
        python -m pip install poetry
    - name: Configure poetry
      run: |
        python -m poetry config virtualenvs.in-project true
    - name: Cache the virtualenv
      uses: actions/cache@v3
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: |
        make install
    - name: Lint project
      run: |
        make lint
    - name: Run unit tests
      run: |
        make test
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: python_junit.xml
      if: ${{ always() }}
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: python_junit.xml
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
